version: '3.2'

services:
  swaggerui:
    image: swaggerapi/swagger-ui
    ports:
      - 80:8080
    hostname: swaggerui
    volumes:
      - ${SWAGGER_PATH}:/app/swagger/
    env_file: .env
    environment:
      - SWAGGER_JSON